### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wpfhtl** [simonmeister/UnFlow#18] opened 2018-03-30 09:41 UTC
The CPU memory goes larger continuously as training until it explode.

**Comment by simonmeister** [comment] 2018-03-30 15:30
Hi, are you training on CPU or GPU? How long did you train? Can you give more details of your environment (os, tensorflow version, ...). I trained for multiple days on different machines and it didn't crash due to a leak.

**Comment by wpfhtl** [comment] 2018-04-02 09:00
Training with GPU, GTX Titan 1080. Ubuntu 16.04, tensorflow 1.2. During training, the GPU memory didn't explode, but the CPU memory increase continuously until 100%

**Comment by wpfhtl** [comment] 2018-04-03 07:04
I noticed that if I set the " tf.app.flags.DEFINE_boolean('debug', True)", the memory consumption will increase fast.

**Comment by simonmeister** [comment] 2018-04-03 07:32
This flag enables recording and writing images to tensorboard, but i don't really know why it should cause a memory leak. On what timescale does the memory increase?

**Comment by wpfhtl** [comment] 2018-04-04 08:22
50000 iteration, it will consume near 30G memory

**Comment by simonmeister** [comment] 2018-04-06 09:05
Is the 30GB with or without the debug Flag? The flag isn't meant to be used during full training. Could you maybe share your complete config.ini file with me?

**Comment by wpfhtl** [comment] 2018-04-12 02:43
The 30GB with the debug Flag, this is the config.ini.
[config.ini.txt](https://github.com/simonmeister/UnFlow/files/1901150/config.ini.txt)

**Comment by simonmeister** [comment] 2018-07-24 15:13
As I was not able to reproduce, I am closing this for now.

**Closed as completed by simonmeister** 2018-07-24 15:13 UTC
